AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SeedBomb Signup API — Handles new customer signups

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage (e.g., dev, staging, prod)

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 128
    Tracing: Active

Resources:
  SignupApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "seedbomb-signup-api-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  SeedbombCustomerSignupEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "seedbomb-signup-bus-${Stage}"

  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "seedbomb-customers-${Stage}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customer_id
          AttributeType: S
        - AttributeName: contact_email
          AttributeType: S
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: customer_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: contact-email-index
          KeySchema:
            - AttributeName: contact_email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: slug-index
          KeySchema:
            - AttributeName: slug
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  HandleNewCustomerSignup:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "signup-handler-${Stage}"
      Handler: functions/handleSignup.handler
      CodeUri: src/
      Events:
        SignupPost:
          Type: Api
          Properties:
            Path: /signup
            Method: POST
            RestApiId: !Ref SignupApi
      Environment:
        Variables:
          STAGE: !Ref Stage
          CUSTOMERS_TABLE_NAME: !Ref CustomersTable
          EVENT_BUS_NAME: !Ref SeedbombCustomerSignupEventBus
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CustomersTable
        - Statement:
            Effect: Allow
            Action:
              - events:PutEvents
            Resource: !GetAtt SeedbombCustomerSignupEventBus.Arn
        - Statement:
            Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Resource: "*"

  SignupWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub seedbomb-signup-acl-${Stage}
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: SignupWebACL
      Rules:
        - Name: RateLimitPerIP
          Priority: 1
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 100
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitPerIP

  WAFAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Sub arn:aws:apigateway:${AWS::Region}::/restapis/${SignupApi}/stages/${Stage}
      WebACLArn: !GetAtt SignupWebACL.Arn

Outputs:
  SignupApiUrl:
    Description: "Signup API endpoint"
    Value: !Sub "https://${SignupApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/signup"
    Export:
      Name: !Sub "SeedbombSignupApiUrl-${Stage}"

  EventBusArn:
    Description: "EventBridge bus ARN for CustomerSignupCompleted events"
    Value: !GetAtt SeedbombCustomerSignupEventBus.Arn
    Export:
      Name: !Sub "SeedbombSignupBusArn-${Stage}"

  CustomersTableName:
    Description: "DynamoDB table for customer profiles"
    Value: !Ref CustomersTable
    Export:
      Name: !Sub "SeedbombCustomersTable-${Stage}"
